Added cloudfront function

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -24,8 +24,18 @@ envsubst < samconfig.toml > samconfig.prod.toml
 # Deploy infrastructure with API
 AWS_PROFILE=${PROFILE} sam deploy --config-file samconfig.prod.toml
 
+if [ $? -ne 0 ]; then
+    echo "SAM deployment failed. Aborting."
+    exit 1
+fi
+
 BUCKET_NAME=$(AWS_PROFILE=${PROFILE} aws cloudformation describe-stacks --stack-name ${STACK_NAME} --region ${REGION} --query "Stacks[0].Outputs[?OutputKey=='StaticFilesBucketName'].OutputValue" --output text)
 CLOUDFRONT_DISTRIBUTION_ID=$(AWS_PROFILE=${PROFILE} aws cloudformation describe-stacks --stack-name ${STACK_NAME} --region ${REGION} --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
 
 # Deploy frontend
 cd modules/frontend/ && AWS_PROFILE=${PROFILE} BUCKET_NAME=${BUCKET_NAME} CLOUDFRONT_DISTRIBUTION_ID=${CLOUDFRONT_DISTRIBUTION_ID} python3 bin/deploy.py
+
+if [ $? -ne 0 ]; then
+    echo "Frontend deployment failed. Aborting."
+    exit 1
+fi
