Made lint checks dynamic and added option to run them per module

diff --git a/bin/run_lint_checks b/bin/run_lint_checks
--- a/bin/run_lint_checks
+++ b/bin/run_lint_checks
@@ -1,10 +1,32 @@
 #!/bin/bash
-docker compose --file test.docker-compose.yml run --rm api_test bash -c \
-  'isort ./ &&
-  echo -e "\033[0;32mIsort check succeeded\033[0m" &&
-  black ./ &&
-  echo -e "\033[0;32mBlack check succeeded\033[0m" &&
-  ruff check --fix --exclude lib ./ &&
-  echo -e "\033[0;32mRuff check succeeded\033[0m" &&
-  mypy ./ &&
-  echo -e "\033[0;32mMypy check succeeded\033[0m"' || exit $?
+
+modules=("$@")
+
+if [ ${#modules[@]} -eq 0 ]; then
+  env_files=($(find ./modules -type f -path "*/.env.test" | sort))
+else
+  env_files=()
+  for module in "${modules[@]}"; do
+    if [ -f "./modules/$module/.env.test" ]; then
+      env_files+=("./modules/$module/.env.test")
+    else
+      echo -e "\033[0;91mModule '$module' not found or missing .env.test file\033[0m"
+      exit 1
+    fi
+  done
+fi
+
+for env_file in "${env_files[@]}"; do
+  source "$env_file"
+  module_name=$(echo "$env_file" | sed -n 's|^./modules/\([^/]*\)/.*|\1|p')
+  echo -e "\n\033[0;94m==== $MODULE_NAME Tests ====\033[0m\n"
+  bash_command="isort $module_name && "
+  bash_command="$bash_command echo -e '\033[0;32mIsort check succeeded\033[0m' && "
+  bash_command="$bash_command black $module_name && "
+  bash_command="$bash_command echo -e '\033[0;32mBlack check succeeded\033[0m' && "
+  bash_command="$bash_command ruff check --fix --exclude lib $module_name && "
+  bash_command="$bash_command echo -e '\033[0;32mRuff check succeeded\033[0m' && "
+  bash_command="$bash_command mypy $module_name && "
+  bash_command="$bash_command echo -e '\033[0;32mMypy check succeeded\033[0m'"
+  docker compose --file test.docker-compose.yml run --rm api_test bash -c "$bash_command" || exit $?
+done
