Added mypy to lintchecks

diff --git a/bin/run_lint_checks b/bin/run_lint_checks
--- a/bin/run_lint_checks
+++ b/bin/run_lint_checks
@@ -3,19 +3,21 @@ RED='\033[0;31m'
 GREEN='\033[0;32m'
 NOCOLOR='\033[0m'
 
-if ! isort --check-only --recursive michalskiba_dev/
+if ! isort --check-only michalskiba_dev/
 then
   echo "${RED}Isort check failed${NOCOLOR}"
   exit 1
 fi
 echo "${GREEN}Isort check succeeded${NOCOLOR}"
+echo
 
-if ! black --check --target-version py311 ./michalskiba_dev/
+if ! black --check ./michalskiba_dev/
 then
   echo "${RED}Black check failed${NOCOLOR}"
   exit 1
 fi
 echo "${GREEN}Black check succeeded${NOCOLOR}"
+echo
 
 if ! ruff check ./michalskiba_dev/
 then
@@ -23,6 +25,15 @@ then
   exit 1
 fi
 echo "${GREEN}Ruff check succeeded${NOCOLOR}"
+echo
+
+if ! mypy --strict michalskiba_dev/
+then
+  echo "${RED}Mypy check failed${NOCOLOR}"
+  exit 1
+fi
+echo "${GREEN}Mypy check succeeded${NOCOLOR}"
+echo
 
 echo
 echo "${GREEN}== Lint checks passed ==${NOCOLOR}"
